apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/gitops-terraform'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: terraform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true